---
title: "WFDS Alaska"
author: "Justin Ziegler"
date: "10/11/2022"
output: html_document
---
# Start 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(spatstat)
library(segmented)
library(cowplot)

load("~/Library/CloudStorage/GoogleDrive-k8rhayes@gmail.com/My Drive/Projects/Reburns/Chapters/Flammabllity/data/fire behavior/results/Copy.rdata")

results <- results %>%
  mutate(fuelWx = paste(fuels,wx,sep = '_'))

results
```

## Design

Complete balanced design with:

-   1x and 3x burned

-   Mean canopy fuels and high canopy fuels

-   Extreme burning conditions and moderate burning conditions

## Wind

```{r}
fuelWx_names <- c( "meanfuel" = "Mean Fuel",
                   "hifuel"   = "High Fuel",
                   "modwx" = "Mod. Wx",
                   "hiwx" = "Hi Wx",
                   "1x" = "Once-burned",
                   "3x" = "Thrice-burned"
                    )


plot1 <- dplyr::select(results,state,fuels, wx, wind) %>%
  unnest(cols = c(wind)) %>%
  dplyr::filter(state == "1x") %>%
  ggplot(aes(x, y,fill = windspd)) +
  geom_raster() + 
  coord_equal() +
  scale_fill_viridis_c(option='mako') +
  facet_grid(wx ~ fuels, 
             labeller = as_labeller(fuelWx_names)) +
  labs(x = 'X, distance from transition (m)',
       y = 'Y (m)',
       title = "A. Once-burned simulations") +
  theme_minimal() 

plot3 <- dplyr::select(results,state,fuels, wx, wind) %>%
  unnest(cols = c(wind)) %>%
  dplyr::filter(state == "3x") %>%
  ggplot(aes(x, y,fill = windspd)) +
  geom_raster() + 
  coord_equal() +
  scale_fill_viridis_c(option='mako') +
  facet_grid(wx~ fuels,
             labeller = as_labeller(fuelWx_names)) +
  labs(x = 'X, distance from transition (m)',
       y = 'Y (m)',
       title = "B. Thrice-burned simulations") +
  theme_minimal() 

plot_grid(plot1, plot3,
          ncol = 1, rel_widths = c(1, 1),
          align = "hv", axis = "l")

# FigX_wind # 750 by 500

plot1 <- dplyr::select(results,sim, state, fuels, wx, wind) %>% 
  filter(state =="1x") %>%
  unnest(cols = c(wind)) %>%
  group_by(fuels, wx, x) %>% 
  summarise(windspd = mean(windspd)) %>%
   ggplot(aes(x, windspd)) + geom_point() +
  facet_grid(wx ~ fuels, 
             labeller = as_labeller(fuelWx_names)) +
  labs(x = 'X, distance from transition (m)',
       y = 'Wind Speed (m/s)',
       title = "A. Once-burned simulations") + 
  theme_minimal()

plot3 <- dplyr::select(results, state, fuels, wx, wind) %>% 
  filter(state =="3x") %>%
  unnest(cols = c(wind)) %>%
  group_by(fuels, wx, x) %>% 
  summarise(windspd = mean(windspd)) %>%
   ggplot(aes(x,windspd)) + geom_point() +
  facet_grid(wx ~ fuels, 
             labeller = as_labeller(fuelWx_names)) +
  labs(x = 'X, distance from transition (m)',
       y = 'Wind Speed (m/s)',
       title = "B. Thrice-burned simulations") + 
  theme_minimal()

plot_grid(plot1, plot3,
          ncol = 1, rel_widths = c(1, 1),
          align = "hv", axis = "l")

#FigX_wind2D # 900 x 300
```

## Surface fuels

```{r fuels, include=FALSE }
stateName <- c("1x" = "Once-burned",
                   "3x" = "Thrice-burned")

group_by(results,state) %>% filter(row_number()==1) %>%
dplyr::select(state,surffuel) %>% unnest() %>%
  ggplot(aes(x,y,fill=class)) +
  geom_raster() +
  theme_minimal() +
  coord_equal() +
  facet_wrap(~state, labeller = as_labeller(stateName))  +
  scale_fill_manual('Surface fuel class', 
                    values = c(topo.colors(10)[10],
                               'forest green'),
                    labels =c('Litter','Litter, Herb, Shrub'))+
   theme(legend.position='bottom') +
  labs(x = 'X, distance from transition (m)', y = 'Y (m)')

# FigX_surfaceFuel # 900 x 350
```

## Canopy Fuels

```{r canfuels, include=FALSE }

# Table 1. fuel loads and fuel density
dplyr::select(results,sim,fulltreelist) %>% unnest() %>%
  group_by(sim) %>%
  filter(x>=0) %>%
  summarise(fuelload = sum(mass)/(70*200),
            fueldensity = sum(mass)/(70*200*quantile(ht,.9))
            )

# not going to use, hard to visualize canopy fuel loads
# dplyr::select(results,sim,fulltreelistmap) %>% unnest() %>%
#   filter(x>=0) %>% rowwise %>%
#   ggplot(aes(x,y,z=mass)) +
#   geom_contour(binwidth = .05) +
#   theme_minimal() +
#   coord_equal() +
#   facet_wrap(~sim) +
#    theme(legend.position='bottom') +
#   labs(x = 'X, distance from transition (m)', y = 'Y (m)')

```

## Tree Consumption


```{r pressure, include=FALSE}
plot1 <- dplyr::select(results,state, fuels, wx, treelist) %>%
  filter(state == "1x") %>%
  unnest(cols = c(treelist)) %>%
  ggplot(aes(x,y,fill = cc, size = maxfuel)) +
  geom_point(pch = 21) +
  coord_equal(expand = FALSE) +
  facet_grid(wx ~ fuels,
             labeller = as_labeller(fuelWx_names)) +
  scale_fill_viridis_b(option = 'B') +
  theme_minimal() + 
    labs(title = "A. Once-burned simulations") +
  theme(plot.margin = c(0.5, 0.5, 0.5, 0.5), "cm")


plot3 <- dplyr::select(results,state, fuels, wx, treelist) %>%
  filter(state == "3x") %>%
  unnest(cols = c(treelist)) %>%
  ggplot(aes(x,y,fill = cc, size = maxfuel)) +
  geom_point(pch = 21) +
  coord_equal(expand = FALSE) +
  facet_grid(wx ~ fuels,
             labeller = as_labeller(fuelWx_names)) +
  scale_fill_viridis_b(option = 'B') +
  theme_minimal() + 
  labs(title = "B. Thrice-burned simulations")

plot_grid(plot1, plot3,
          ncol = 1, rel_widths = c(1, 1),
          align = "hv", axis = "l")

# FigX_canopyC  # 1000 by 600

plot1 <- dplyr::select(results, state, fuels, wx, treelist) %>% 
  filter(state == "1x") %>%
  unnest(col = c(treelist)) %>%
  ggplot(aes(x,cc, size = maxfuel)) +
  geom_point(pch=21) +
  coord_cartesian(expand = FALSE)  +
  theme_minimal()+
  facet_grid(wx ~ fuels,
             labeller = as_labeller(fuelWx_names)) +
  geom_line( data = dplyr::select(results, state, fuels, wx,
                                  segmentpredict) %>%
               filter(state == "1x") %>%
      unnest(cols = c(segmentpredict)),
    lwd = 1,
    col='blue') + 
  labs(x = 'X, distance from transition (m)', 
       y = 'Canopy Consumption (%)',
       title = "A. Once-burned simulations")

plot3 <- dplyr::select(results,state,fuels, wx, treelist) %>% 
  filter(state == "3x") %>%
  unnest(col = c(treelist)) %>%
  ggplot(aes(x,cc, size = maxfuel)) +
  geom_point(pch=21) +
  coord_cartesian(expand = FALSE)  +
  theme_minimal()+
  facet_grid(wx ~ fuels,
             labeller = as_labeller(fuelWx_names)) +
  geom_line(data = dplyr::select(results, state, fuels, wx,
                                  segmentpredict) %>%
              filter(state == "3x") %>%
      unnest(cols = c(segmentpredict)),
    lwd = 1,
    col='blue') + 
  labs(x = 'X, distance from transition (m)', 
       y = 'Canopy Consumption (%)',
       title = "B. Thrice-burned simulations")

plot_grid(plot1, plot3,
          ncol = 1, rel_widths = c(1, 1),
          align = "hv", axis = "l")

# FigX_canopyC_2D # 1200 by 300
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Time of Arrival

```{r, include=FALSE}

plot1 <- group_by(results, state, fuels, wx) %>% 
  filter(state == "1x") %>%
  filter(row_number() == 1) %>%
  dplyr::select(state,surffuel) %>% 
  unnest() %>%
  ggplot(aes(x, y, fill = class)) +
  geom_raster() +
  theme_minimal() +
  coord_equal(expand = FALSE) +
  facet_grid(wx ~ fuels, 
             labeller = as_labeller(fuelWx_names))  +
  scale_fill_manual('Surface fuel class', 
                    values = c(topo.colors(10)[10],
                               'forest green'),
                    labels =c('Litter only',
                              'Litter, Herb, Shrub'))+
   theme(legend.position='none') +
  labs(x = 'X, distance from transition (m)', 
       y = 'Y (m)', 
       title = "A. Once-burned scenario") +
  geom_raster(data = dplyr::select(results, state,
                                   fuels, wx, bndry) %>% 
                filter(state == "1x") %>%
                unnest() %>% na.omit(),
    aes(x,y+25,z = toa), 
    inherit.aes = FALSE) +
  geom_contour(data = dplyr::select(results, state,
                                    fuels, wx, bndry) %>%
                 filter(state == "1x") %>%
                 unnest(),
    aes(x,y+25,z = toa),
    binwidth = 10000, 
    inherit.aes = FALSE) +
  geom_contour(data = dplyr::select(results, state,
                                    fuels, wx, bndry) %>%
                 filter(state == "1x") %>%
                 unnest() %>% 
                 group_by(fuels, wx),
    aes(x, y+25, z = toa),
    binwidth = 10, 
    inherit.aes = FALSE)

plot1
plot3 <- group_by(results, state, fuels, wx) %>% 
  filter(state == "3x") %>%
  filter(row_number() == 1) %>%
  dplyr::select(state,surffuel) %>% 
  unnest(cols = c(surffuel)) %>%
  ggplot(aes(x, y, fill = class)) +
  geom_raster() +
  theme_minimal() +
  coord_equal(expand = FALSE) +
  facet_grid(wx ~ fuels, 
             labeller = as_labeller(fuelWx_names))  +
  scale_fill_manual('Surface fuel class', 
                    values = c(topo.colors(10)[10],
                               'forest green'),
                    labels =c('Litter only',
                              'Litter, Herb, Shrub'))+
   theme(legend.position='bottom') +
  labs(x = 'X, distance from transition (m)', 
       y = 'Y (m)',
       title = "B. Thrice-burned scenario") +
  geom_raster(data = dplyr::select(results, state,
                                   fuels, wx, bndry) %>% 
                filter(state == "3x") %>%
                unnest(cols = c(bndry)) %>% na.omit(),
    aes(x, y+25, z = toa), 
    inherit.aes = FALSE) +
  geom_contour(data = dplyr::select(results, state,
                                    fuels, wx, bndry) %>%
                 filter(state == "3x") %>%
                 unnest(cols = c(bndry)),
    aes(x, y+25, z = toa),
    binwidth = 10000, 
    inherit.aes = FALSE) +
  geom_contour(data = dplyr::select(results, state,
                                    fuels, wx, bndry) %>%
                 filter(state == "3x") %>%
                 unnest(cols = c(bndry)) %>% 
                 group_by(fuels, wx),
    aes(x, y+25, z = toa),
    binwidth = 10, 
    inherit.aes = FALSE)

plot3

plot_grid(plot1, plot3,
          ncol = 1, rel_widths = c(1, 2),
          align = "hv", axis = "l")

# FigX_time # 3000 by 500

```

## Rate of Spread

```{r, include=FALSE}

dplyr::select(results, state, fuelWx, ros) %>% 
  unnest(cols = c(ros)) %>%
  ggplot(aes(x,ros)) +
  geom_line()  +
  theme_minimal() +
  facet_grid(state ~ fuelWx, labeller = as_labeller(fuelWx_names))  +
  labs(x = 'X, distance from transition (m)',
       y = 'Rate of Spread (m/s)')

# FigX_ros # 1000 by 300

```
